server:
  port: 8001 # 服务端口
spring:
  application:
    name: service_edu # 服务名
  profiles:
    active: dev # 环境设置 dev、test、prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8 # 北京时间东八区
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 设置接口返回的json数据的时间字段的格式
    time-zone: GMT+8 # 设置接口返回的json数据的时间字段的时区（东八区）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看 sql 语句日志
