server:
  port: 8160 # 服务端口

spring:
  application:
    name: service-ucenter # 服务名(不能加下划线)
  profiles:
    active: dev # 环境设置 dev、test、prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8 # 北京时间东八区
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 设置接口返回的json数据的时间字段的格式
    time-zone: GMT+8 # 设置接口返回的json数据的时间字段的时区（东八区）
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 整合swagger需要配置

  redis:
    host: localhost
    port: 6390
    password: 123456
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞等待时间（负数表示没限制）
        max-idle: 5
        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看 sql 语句日志
  mapper-locations: classpath:whut/yy/service_ucenter/mapper/xml/*.xml
#  type-aliases-package: whut.yy.service_ucenter.entity.vo # 实体类别名

wx:
  open:
    app-id: 填写你的id # 微信开放平台 appid
    app-secret: 填写你的密钥 # 微信开放平台 appsecret
    redirect-url: 填写你的回调地址 # 微信开放平台 重定向url