server:
  port: 8007 # 服务端口

spring:
  application:
    name: service-order # 服务名(不能加下划线)
  profiles:
    active: dev # 环境设置 dev、test、prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8 # 北京时间东八区
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 设置接口返回的json数据的时间字段的格式
    time-zone: GMT+8 # 设置接口返回的json数据的时间字段的时区（东八区）
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  redis:
#    host: localhost
#    port: 6390
#    password: 123456
#    database: 0
#    timeout: 1800000
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1 #最大阻塞等待时间（负数表示没限制）
#        max-idle: 5
#        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看 sql 语句日志
  mapper-locations: classpath:whut/yy/service_order/mapper/xml/*.xml
#  type-aliases-package: whut.yy.service_edu.entity.vo # 实体类别名

#feign:
#  sentinel:
#    enabled: true # 熔断配置

alipay:
  appId: 2021000122604773
  appPrivateKey: 你的应用私钥
  alipayPublicKey: 你的支付宝公钥
  #支付成功之后的回调页面，只是一个友好页面。-同步
  #  returnUrl: http://localhost:8007/return.html
  #支付成功的接口回调，要是外网能访问的 -异步
  notifyUrl: http://bt2r8h.natappfree.cc/service_order/payLog/notify

