server:
  port: 8002 # 服务端口
spring:
  application:
    name: service_oss # 服务名
  profiles:
    active: dev # 环境设置 dev、test、prod
  servlet:
    multipart:
      max-file-size: 10MB # 设置文件最大上传长度
      max-request-size: 100MB

# 阿里云 OSS
# 不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: 填写你的节点
      keyid: 填写你的id
      keysecret: 填写你的密钥
      bucketname: 填写你的bucketname